# Generated by Django 5.1.5 on 2025-03-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineblog', '0003_post_image_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
